# Generated by Django 5.2.8 on 2025-11-15 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore1', '0002_book_url_alter_book_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='url',
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.IntegerField(),
        ),
    ]
