# Generated by Django 5.2.8 on 2025-11-17 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore1', '0003_remove_book_url_alter_book_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
    ]
