# Generated by Django 5.2.8 on 2025-11-17 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore1', '0004_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
