# Generated by Django 5.2.8 on 2025-11-17 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore1', '0007_alter_userdetails_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('total_amount', models.IntegerField()),
                ('books', models.ManyToManyField(to='bookstore1.book')),
            ],
        ),
    ]
